### ISSUE TITLE
No my Buttons and no useable Beoremote one, Balans and Theatre entities

### ISSUE THREAD

**Issue by Omebeb** [bang-olufsen/bang_olufsen-hacs#26]
I have a problem with the B&O Mozart integration within Home Assistant. For quite some time, I’ve had a perfect integration with my B&O Theatre, Balance, and Beolab 8. However, in recent weeks, I’ve lost a lot of functionality, such as the absence of "My Buttons" and all Beoremote commands.
 Is there antything to do?

Regards,
Martijn

**Comment by cklit** [comment]
Hi Martijn,

Thanks for using the custom Bang & Olufsen integration for Home Assistant. In case you don't know, this is kind of the beta-channel for the official Bang & Olufsen integration for Home Assistant.

Favourites are now implemented as an Action, also shown in the documentation:

```
service: media_player.play_media
target:
  entity_id: media_player.beosound_balance_12345678
data:
  media_content_type: favourite
  media_content_id: 1 
```


Here is an example of how you can implement it to the front-end:
![Screenshot 2024-12-09 at 22 00 10](https://github.com/user-attachments/assets/c036e752-56eb-4112-a48e-29e53c2c881a)


```
type: horizontal-stack
cards:
  - type: tile
    entity: media_player.beosound_theatre_11223344
    name: Fav 1
    icon: mdi:numeric-1-circle
    hide_state: true
    tap_action:
      action: perform-action
      perform_action: media_player.play_media
      target:
        entity_id: media_player.beosound_theatre_11223344
      data:
        media_content_id: "1"
        media_content_type: favourite
    icon_tap_action:
      action: none
    hold_action:
      action: none
  - type: tile
    entity: media_player.beosound_theatre_11223344
    name: Fav 2
    icon: mdi:numeric-2-circle
    hide_state: true
    tap_action:
      action: perform-action
      perform_action: media_player.play_media
      target:
        entity_id: media_player.beosound_theatre_11223344
      data:
        media_content_id: "2"
        media_content_type: favourite
    icon_tap_action:
      action: none
    hold_action:
      action: none
  - type: tile
    entity: media_player.beosound_theatre_11223344
    name: Fav 3
    icon: mdi:numeric-3-circle
    hide_state: true
    tap_action:
      action: perform-action
      perform_action: media_player.play_media
      target:
        entity_id: media_player.beosound_theatre_11223344
      data:
        media_content_id: "3"
        media_content_type: favourite
    icon_tap_action:
      action: none
    hold_action:
      action: none
  - type: tile
    entity: media_player.beosound_theatre_11223344
    name: Fav 4
    icon: mdi:numeric-4-circle
    hide_state: true
    tap_action:
      action: perform-action
      perform_action: media_player.play_media
      target:
        entity_id: media_player.beosound_theatre_11223344
      data:
        media_content_id: "4"
        media_content_type: favourite
    icon_tap_action:
      action: none
    hold_action:
      action: none

```

Regarding the Light and Control commands, this structure has also changed. Your speaker that has a remote control attached to it, will now have the remote as a separate device, where you can enable events for the buttons you would like to utilise.
￼![Screenshot 2024-12-09 at 21 54 38](https://github.com/user-attachments/assets/218c1588-cab2-4c4b-bd6a-8f0ee54c530d)

Alternatively, you can try one of the Blueprints for Mozart Platform-based products found here: [cklit.dk](http://cklit.dk/) (Light and Shade control).  

We realise that these things might be inconvenient for you, but we try to follow the guidelines for integrations provided by Home Assistant for best compatibility. Hope this answers your questions :)
